name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200
      - name: Create WOTLK Package
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath -m .pkgmeta-wrath -w 0 -p 0 -a 0
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
